export const contracts = [{ value: "成約" }, { value: "不成約" }]
export const gender = [{ value: "男性" }, { value: "女性" }]
export const reasonA = [
    { value: "折込" },
    { value: "店舗前" },
    { value: "顧客" },
    { value: "HP" },
    { value: "紹介" },
    { value: "ポスティング" },
    { value: "LAIN" },
    { value: "未確認" },
]
export const reasonB = [
    { value: "朝日" },
    { value: "読売" },
    { value: "毎日" },
    { value: "産経" },
    { value: "静岡" },
    { value: "中日" },
    { value: "日経" },
    { value: "店舗前" },
    { value: "顧客" },
    { value: "HP" },
    { value: "紹介" },
    { value: "LAIN" },
    { value: "未確認" },
]
export const productA = [
    { value: "貴金属" },
    { value: "金券" },
    { value: "切手" },
    { value: "ブランド" },
    { value: "古銭" },
    { value: "通貨" },
    { value: "テレカ" },
    { value: "カメラ" },
    { value: "携帯" },
    { value: "酒" },
    { value: "その他" },

]
export const productB = [
    { value: "バッグ" },
    { value: "財布" },
    { value: "小物" },
    { value: "アクセサリー" },
    { value: "時計" },
    { value: "その他" },
    { value: "切手バラ（高）" },
    { value: "切手バラ（小）" },
    { value: "切手シート(高）" },
    { value: "切手シート（小）" },
    { value: "中国切手" },
    { value: "切手その他" },
    { value: "外国銭" },
    { value: "ダイヤ" },
    { value: "MD" },
    { value: "色石" },
    { value: "精錬" },
    { value: "50" },
    { value: "105" },
]
export const brands = [
    { value: 'IWC' },
    { value: 'YSL' },
    { value: 'LV' },
    { value: 'VACHERON export constANTIN' },
    { value: 'V&A' },
    { value: 'WALTHAM' },
    { value: 'HERMES' },
    { value: 'MCM' },
    { value: 'ETRO' },
    { value: 'AUDEMARS PIGUET' },
    { value: 'OMEGA' },
    { value: 'Cartier' },
    { value: 'GUCCI' },
    { value: 'CD' },
    { value: 'Chloe' },
    { value: 'kate spade' },
    { value: 'COACH' },
    { value: 'GOYARD' },
    { value: 'CHOPARD' },
    { value: 'CHAUMET' },
    { value: 'CHANEL' },
    { value: 'GIVENCHY' },
    { value: 'CELINE' },
    { value: 'SEIKO' },
    { value: 'TAG HEUER' },
    { value: 'TIFFANY' },
    { value: 'TUDOR' },
    { value: 'TORY BURCH' },
    { value: 'NB' },
    { value: 'BURBERRY' },
    { value: 'PATEK PHILIPPE' },
    { value: 'PANERAI' },
    { value: 'BALENCIAGA' },
    { value: 'HUNTING WORLD' },
    { value: 'BALLY' },
    { value: 'PIAGET' },
    { value: 'FRANCK MULLER' },
    { value: 'BVLGARI' },
    { value: 'BREITLING' },
    { value: 'PRADA' },
    { value: 'Ferragamo' },
    { value: 'FENDI' },
    { value: 'BOTTEGA' },
    { value: 'miumiu' },
    { value: 'RADO' },
    { value: 'LONGINES' },
    { value: 'ROLEX' },
    { value: 'LOEWE' },
]
export const ranks = [
    { value: 'A' },
    { value: 'AB' },
    { value: 'B上' },
    { value: 'B' },
    { value: 'B下' },
    { value: 'BC' },
    { value: 'C' },
]
export const metals = [
    { value: 'SV925' },
    { value: 'K18' },
    { value: 'Pt900' },
    { value: 'Pt850' },
    { value: 'K18WG' },
    { value: 'K14WG' },
    { value: 'K18石付' },
    { value: 'Pt900石付' },
    { value: 'Pt850石付' },
    { value: 'K24C' },
    { value: 'K24' },
    { value: 'K22' },
    { value: 'K21.6' },
    { value: 'K20' },
    { value: 'K14' },
    { value: 'K10' },
    { value: 'K9' },
    { value: 'Pt' },
    { value: 'Pm' },
    { value: 'Pt1000' },
    { value: 'Pt950' },
    { value: 'Pt900/K18' },
    { value: 'Pt850/K18' },
    { value: 'SV' },
    { value: 'SV1000' },
    { value: '金歯' },
]
export const sales = [
    { value: 'Jマーケット' },
    { value: 'GA' },
    { value: 'BB' },
    { value: 'オークション' },
]

export const payments = [
    { value: 'かんたん決済' },
    { value: 'ウォレット決済' },
    { value: '銀行振込' },
]